---

#|  Install and configure Ansible

- name: main - Include OS-Specific Variables
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
    - 'default.yml'
  when: ansible_role_enabled | bool
  tags: [ 'ansible', 'ansible-install' ]

- name: main - Install Ansible from source
  include: '{{ found_item }}'
  with_first_found:
    - 'install/{{ ansible_role_install_method }}-{{ ansible_distribution }}.yml'
    - 'install/{{ ansible_role_install_method }}-{{ ansible_os_family }}.yml'
    - 'install/{{ ansible_role_install_method }}-default.yml'
  when: ansible_role_enabled | bool
  loop_control:
    loop_var: found_item
  tags: [ 'ansible', 'ansible-install' ]

- name: main - Configure Ansible
  include: '{{ found_item }}'
  with_first_found:
    - 'config/{{ ansible_distribution }}.yml'
    - 'config/{{ ansible_os_family }}.yml'
    - 'config/default.yml'
  when: (ansible_role_enabled | bool) and
        (ansible_role_configure_ansible | bool)
  loop_control:
    loop_var: found_item
  tags: [ 'ansible', 'ansible-config' ]


  