---

- name: config/default - Divert original ansible.cfg
  command: dpkg-divert --quiet --local --divert /etc/ansible/ansible.cfg.dpkg-divert --rename /etc/ansible/ansible.cfg
  args:
    creates: '/etc/ansible/ansible.cfg.dpkg-divert'

- name: config/default - Configure /etc/ansible/ansible.cfg
  template:
    src: 'etc-ansible-ansible.cfg.j2'
    dest: '/etc/ansible/ansible.cfg'
    owner: 'root'
    group: 'root'
    mode: '0644'